version: '3.7'

services:

  watchtower:
    container_name: watchtower
    image: index.docker.io/containrrr/watchtower:latest
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '~/.docker/config.json:/config.json'
    environment: 
      - WATCHTOWER_NOTIFICATIONS=slack
      - 'WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=https://hooks.slack.com/services/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'
      - WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=Docker_Watchtower
      - 'WATCHTOWER_NOTIFICATION_SLACK_CHANNEL=#updates'
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=true
      - WATCHTOWER_POLL_INTERVAL=60

  clientsit:
    # container_name: video-party-client
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: clientsit
    image: index.docker.io/varungujarathi9/video-party-client:sit
    ports:
      - 3001:3000
    
  clientuat:
    # container_name: video-party-client
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: clientuat
    image: index.docker.io/varungujarathi9/video-party-client:uat
    ports:
      - 3002:80

  clientprod:
    # container_name: video-party-client
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: clientprod
    image: index.docker.io/varungujarathi9/video-party-client:latest
    ports:
      - 80:80
    networks:
      - prod  

  serversit:
    # container_name: video-party-server
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: serversit
    image: index.docker.io/varungujarathi9/video-party-server:sit
    ports:
      - 5001:5000

  serveruat:
    # container_name: video-party-server
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: serveruat
    image: index.docker.io/varungujarathi9/video-party-server:uat
    ports:
      - 5002:5000

  serverprod:
    # container_name: video-party-client
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: serverprod
    image: index.docker.io/varungujarathi9/video-party-server:latest
    ports:
      - 1793:5000
    networks:
      - prod